# Generated by Django 5.0.1 on 2024-01-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer_explanation',
            field=models.TextField(default='anything'),
            preserve_default=False,
        ),
    ]
