# Generated by Django 5.0.1 on 2024-01-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_question_id_questionanswers_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.TextField(),
        ),
    ]
