# Generated by Django 5.0.1 on 2024-01-17 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_questions_answer_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.CharField(choices=[('30', '30 minutes'), ('60', '1 hour'), ('90', '1 hour 30 minutes'), ('120', '2 hours')], max_length=3)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.courses')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='exam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
