# Generated by Django 5.0 on 2024-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0005_alter_questions_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="examuser",
            name="subscription_active",
            field=models.BooleanField(default=True),
        ),
    ]
