# Generated by Django 5.0.1 on 2024-02-06 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCheckoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('MerchantRequestID', models.CharField(max_length=255)),
                ('CheckoutRequestID', models.CharField(max_length=255)),
                ('ResponseCode', models.IntegerField(default=0)),
                ('ResponseDescription', models.CharField(max_length=1000)),
                ('CustomerMessage', models.CharField(max_length=100)),
                ('AmountExpected', models.IntegerField(default=0)),
                ('PhoneNumber', models.CharField(max_length=255, null=True)),
                ('ProcessingStatus', models.CharField(choices=[('Processed Successfully', 'Processed Successfully'), ('Processed Unsuccessfully', 'Processed Unsuccessfully')], max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('UserEmail', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaResponseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_data', models.JSONField(default=dict)),
                ('response_description', models.CharField(max_length=1000)),
                ('response_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestID', models.CharField(max_length=255)),
                ('CheckoutRequestID', models.CharField(max_length=255)),
                ('ResultCode', models.IntegerField(default=0)),
                ('ResultDesc', models.CharField(max_length=1000)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TransactionTimeStamp', models.CharField(max_length=255, null=True)),
                ('TransactionDate', models.DateTimeField()),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('MpesaReceiptNumber', models.CharField(max_length=255)),
                ('MpesaUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated')], max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionpackage')),
            ],
        ),
    ]
