# Generated by Django 5.0 on 2024-01-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_mpesaresponsedata_mpesatransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Deactivated", "Deactivated")],
                max_length=255,
                null=True,
            ),
        ),
    ]
