# Generated by Django 5.0 on 2024-01-31 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_mpesacheckoutrequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mpesacheckoutrequest",
            old_name="ResultCode",
            new_name="ResponseCode",
        ),
        migrations.RenameField(
            model_name="mpesacheckoutrequest",
            old_name="ResultDescription",
            new_name="ResponseDescription",
        ),
    ]
