# Generated by Django 5.0 on 2024-01-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0005_rename_resultcode_mpesacheckoutrequest_responsecode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesacheckoutrequest",
            name="AmountExpected",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mpesacheckoutrequest",
            name="PhoneNumber",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
