# Generated by Django 5.0 on 2024-01-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_mpesacheckoutrequest_amountexpected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesacheckoutrequest",
            name="ProcessingStatus",
            field=models.CharField(
                choices=[
                    ("Processed Successfully", "Processed Successfully"),
                    ("Processed Unsuccessfully", "Processed Unsuccessfully"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mpesacheckoutrequest",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
