# Generated by Django 5.0 on 2024-01-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_mpesacheckoutrequest_processingstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesacheckoutrequest",
            name="UserEmail",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
